/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardRouteImport } from './routes/board'
import { Route as ConflictsRouteImport } from './routes/conflicts'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as HealthRouteImport } from './routes/health'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as LatencyRouteImport } from './routes/latency'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as ModeRouteImport } from './routes/mode'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as RaceRouteImport } from './routes/race'
import { Route as ReadyRouteImport } from './routes/ready'
import { Route as ReplayRouteImport } from './routes/replay'
import { Route as MatchesIdRouteImport } from './routes/matches/$id'
import { Route as ProvidersIdRouteImport } from './routes/providers/$id'
import { Route as SseLiveRouteImport } from './routes/sse/live'
import { Route as MatchesIdEventsRouteImport } from './routes/matches/$id/events'
import { Route as ProvidersIdHealthRouteImport } from './routes/providers/$id/health'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const ConflictsRoute = ConflictsRouteImport.update({
  id: '/conflicts',
  path: '/conflicts',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LatencyRoute = LatencyRouteImport.update({
  id: '/latency',
  path: '/latency',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeRoute = ModeRouteImport.update({
  id: '/mode',
  path: '/mode',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const RaceRoute = RaceRouteImport.update({
  id: '/race',
  path: '/race',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyRoute = ReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayRoute = ReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIdRoute = MatchesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MatchesRoute,
} as any)
const ProvidersIdRoute = ProvidersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProvidersRoute,
} as any)
const SseLiveRoute = SseLiveRouteImport.update({
  id: '/sse/live',
  path: '/sse/live',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIdEventsRoute = MatchesIdEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => MatchesIdRoute,
} as any)
const ProvidersIdHealthRoute = ProvidersIdHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => ProvidersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/conflicts': typeof ConflictsRoute
  '/credentials': typeof CredentialsRoute
  '/health': typeof HealthRoute
  '/journal': typeof JournalRoute
  '/latency': typeof LatencyRoute
  '/matches': typeof MatchesRouteWithChildren
  '/metrics': typeof MetricsRoute
  '/mode': typeof ModeRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/race': typeof RaceRoute
  '/ready': typeof ReadyRoute
  '/replay': typeof ReplayRoute
  '/matches/$id': typeof MatchesIdRouteWithChildren
  '/providers/$id': typeof ProvidersIdRouteWithChildren
  '/sse/live': typeof SseLiveRoute
  '/matches/$id/events': typeof MatchesIdEventsRoute
  '/providers/$id/health': typeof ProvidersIdHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/conflicts': typeof ConflictsRoute
  '/credentials': typeof CredentialsRoute
  '/health': typeof HealthRoute
  '/journal': typeof JournalRoute
  '/latency': typeof LatencyRoute
  '/matches': typeof MatchesRouteWithChildren
  '/metrics': typeof MetricsRoute
  '/mode': typeof ModeRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/race': typeof RaceRoute
  '/ready': typeof ReadyRoute
  '/replay': typeof ReplayRoute
  '/matches/$id': typeof MatchesIdRouteWithChildren
  '/providers/$id': typeof ProvidersIdRouteWithChildren
  '/sse/live': typeof SseLiveRoute
  '/matches/$id/events': typeof MatchesIdEventsRoute
  '/providers/$id/health': typeof ProvidersIdHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/conflicts': typeof ConflictsRoute
  '/credentials': typeof CredentialsRoute
  '/health': typeof HealthRoute
  '/journal': typeof JournalRoute
  '/latency': typeof LatencyRoute
  '/matches': typeof MatchesRouteWithChildren
  '/metrics': typeof MetricsRoute
  '/mode': typeof ModeRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/race': typeof RaceRoute
  '/ready': typeof ReadyRoute
  '/replay': typeof ReplayRoute
  '/matches/$id': typeof MatchesIdRouteWithChildren
  '/providers/$id': typeof ProvidersIdRouteWithChildren
  '/sse/live': typeof SseLiveRoute
  '/matches/$id/events': typeof MatchesIdEventsRoute
  '/providers/$id/health': typeof ProvidersIdHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/board'
    | '/conflicts'
    | '/credentials'
    | '/health'
    | '/journal'
    | '/latency'
    | '/matches'
    | '/metrics'
    | '/mode'
    | '/providers'
    | '/race'
    | '/ready'
    | '/replay'
    | '/matches/$id'
    | '/providers/$id'
    | '/sse/live'
    | '/matches/$id/events'
    | '/providers/$id/health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/board'
    | '/conflicts'
    | '/credentials'
    | '/health'
    | '/journal'
    | '/latency'
    | '/matches'
    | '/metrics'
    | '/mode'
    | '/providers'
    | '/race'
    | '/ready'
    | '/replay'
    | '/matches/$id'
    | '/providers/$id'
    | '/sse/live'
    | '/matches/$id/events'
    | '/providers/$id/health'
  id:
    | '__root__'
    | '/'
    | '/board'
    | '/conflicts'
    | '/credentials'
    | '/health'
    | '/journal'
    | '/latency'
    | '/matches'
    | '/metrics'
    | '/mode'
    | '/providers'
    | '/race'
    | '/ready'
    | '/replay'
    | '/matches/$id'
    | '/providers/$id'
    | '/sse/live'
    | '/matches/$id/events'
    | '/providers/$id/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardRoute: typeof BoardRoute
  ConflictsRoute: typeof ConflictsRoute
  CredentialsRoute: typeof CredentialsRoute
  HealthRoute: typeof HealthRoute
  JournalRoute: typeof JournalRoute
  LatencyRoute: typeof LatencyRoute
  MatchesRoute: typeof MatchesRouteWithChildren
  MetricsRoute: typeof MetricsRoute
  ModeRoute: typeof ModeRoute
  ProvidersRoute: typeof ProvidersRouteWithChildren
  RaceRoute: typeof RaceRoute
  ReadyRoute: typeof ReadyRoute
  ReplayRoute: typeof ReplayRoute
  SseLiveRoute: typeof SseLiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conflicts': {
      id: '/conflicts'
      path: '/conflicts'
      fullPath: '/conflicts'
      preLoaderRoute: typeof ConflictsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latency': {
      id: '/latency'
      path: '/latency'
      fullPath: '/latency'
      preLoaderRoute: typeof LatencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mode': {
      id: '/mode'
      path: '/mode'
      fullPath: '/mode'
      preLoaderRoute: typeof ModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/race': {
      id: '/race'
      path: '/race'
      fullPath: '/race'
      preLoaderRoute: typeof RaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ready': {
      id: '/ready'
      path: '/ready'
      fullPath: '/ready'
      preLoaderRoute: typeof ReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay': {
      id: '/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof ReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$id': {
      id: '/matches/$id'
      path: '/$id'
      fullPath: '/matches/$id'
      preLoaderRoute: typeof MatchesIdRouteImport
      parentRoute: typeof MatchesRoute
    }
    '/providers/$id': {
      id: '/providers/$id'
      path: '/$id'
      fullPath: '/providers/$id'
      preLoaderRoute: typeof ProvidersIdRouteImport
      parentRoute: typeof ProvidersRoute
    }
    '/sse/live': {
      id: '/sse/live'
      path: '/sse/live'
      fullPath: '/sse/live'
      preLoaderRoute: typeof SseLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$id/events': {
      id: '/matches/$id/events'
      path: '/events'
      fullPath: '/matches/$id/events'
      preLoaderRoute: typeof MatchesIdEventsRouteImport
      parentRoute: typeof MatchesIdRoute
    }
    '/providers/$id/health': {
      id: '/providers/$id/health'
      path: '/health'
      fullPath: '/providers/$id/health'
      preLoaderRoute: typeof ProvidersIdHealthRouteImport
      parentRoute: typeof ProvidersIdRoute
    }
  }
}

interface MatchesIdRouteChildren {
  MatchesIdEventsRoute: typeof MatchesIdEventsRoute
}

const MatchesIdRouteChildren: MatchesIdRouteChildren = {
  MatchesIdEventsRoute: MatchesIdEventsRoute,
}

const MatchesIdRouteWithChildren = MatchesIdRoute._addFileChildren(
  MatchesIdRouteChildren,
)

interface MatchesRouteChildren {
  MatchesIdRoute: typeof MatchesIdRouteWithChildren
}

const MatchesRouteChildren: MatchesRouteChildren = {
  MatchesIdRoute: MatchesIdRouteWithChildren,
}

const MatchesRouteWithChildren =
  MatchesRoute._addFileChildren(MatchesRouteChildren)

interface ProvidersIdRouteChildren {
  ProvidersIdHealthRoute: typeof ProvidersIdHealthRoute
}

const ProvidersIdRouteChildren: ProvidersIdRouteChildren = {
  ProvidersIdHealthRoute: ProvidersIdHealthRoute,
}

const ProvidersIdRouteWithChildren = ProvidersIdRoute._addFileChildren(
  ProvidersIdRouteChildren,
)

interface ProvidersRouteChildren {
  ProvidersIdRoute: typeof ProvidersIdRouteWithChildren
}

const ProvidersRouteChildren: ProvidersRouteChildren = {
  ProvidersIdRoute: ProvidersIdRouteWithChildren,
}

const ProvidersRouteWithChildren = ProvidersRoute._addFileChildren(
  ProvidersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardRoute: BoardRoute,
  ConflictsRoute: ConflictsRoute,
  CredentialsRoute: CredentialsRoute,
  HealthRoute: HealthRoute,
  JournalRoute: JournalRoute,
  LatencyRoute: LatencyRoute,
  MatchesRoute: MatchesRouteWithChildren,
  MetricsRoute: MetricsRoute,
  ModeRoute: ModeRoute,
  ProvidersRoute: ProvidersRouteWithChildren,
  RaceRoute: RaceRoute,
  ReadyRoute: ReadyRoute,
  ReplayRoute: ReplayRoute,
  SseLiveRoute: SseLiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
